settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-graphql-api
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
- name: my-subie-api
  path: /Users/anagorny/go/src/my-subie-api
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
