import RARE from '../../../icons/tagIcons/RARE.svg'
import EXTRARARE from '../../../icons/tagIcons/EXTRARARE.svg'
import HOT from '../../../icons/tagIcons/HOT.svg'
import BRANDED from '../../../icons/tagIcons/BRANDED.svg'
import BRANDNEW from '../../../icons/tagIcons/BRANDNEW.svg'
import NEWARRIVALS from '../../../icons/tagIcons/NEWARRIVALS.svg'
import FRONT from '../../../icons/tagIcons/FRONT.svg'
import INTERIOR from '../../../icons/tagIcons/INTERIOR.svg'
import SEDAN from '../../../icons/tagIcons/SEDAN.svg'
import SIDE from '../../../icons/tagIcons/SIDE.svg'
import WAGON from '../../../icons/tagIcons/WAGON.svg'
import REAR from '../../../icons/tagIcons/REAR.svg'
import DISCOUNTED from '../../../icons/tagIcons/DISCOUNTED.svg'

export {RARE, EXTRARARE, HOT, BRANDED, BRANDNEW, NEWARRIVALS, FRONT, INTERIOR, SEDAN, SIDE, WAGON, REAR, DISCOUNTED};
