export const models = [
    'LEGACY & OUTBACK',
    'IMPREZA',
    'FORESTER',
    'MERCH',
    'MISC',
]
export const gens = [
    '2GEN (BG/BD/BK) 1993-1999',
    '3GEN (BH/BE) 1999-2004',
    '4GEN (BP/BL) 2003-2009',
    'OTHER LEGACY & OB)',
    'MEANEYE (GC/GF/GM) 1992-2000',
    'BUGEYE (GD/GG) 2000-2004',
    'BLOBEYE (GD/GG) 2003-2005',
    'OTHER IMPREZA',
    'SF 1997-2002',
    'SG 2002-2007',
    'OTHER FORESTER',
    'STICKERS',
    'SHIRTS',
    'POSTERS',
    'OTHER STUFF',
]
export const tags = [
    '#FRONT',
    '#REAR',
    '#SIDE',
    '#INTERIOR',
    '#SEDAN',
    '#WAGON',
    '#HOT',
    '#RARE',
    '#EXTRARARE',
    '#BRANDNEW',
    '#DISCOUNTED',
    '#NEWARRIVALS',
    '#BRANDED',
    '#BYMYSUBIE',
    '#UNDER100',
]
